name: Build and push

run-name: Build ${{ github.ref_name }} requested by ${{ github.actor }} 🚀

on:
    workflow_call:
      inputs:
        image_name:
          description: "Image name"
          required: true
          type: string
        os_version:
          description: "Pipeline operating system"
          required: false
          type: string
          default: "ubuntu-latest"
        odoo_version:
          description: "Odoo Version"
          required: false
          type: string
          default: "odoo_version.txt"
      secrets:
        DOCKER_USERNAME:
          required: true
        DOCKER_PASSWORD:
          required: true
        SUBMODULE_PRIVATE_TOKEN:
          required: true
        LIL_DOCKER_USERNAME:
          required: true
        LIL_DOCKER_PASSWORD:
          required: true


jobs:
  build-and-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ${{ inputs.os_version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_PRIVATE_TOKEN }}

      - name: Prepare repository
        id: prepare-repository
        uses: apikcloud/prepare-repository-action@v1
        with:
          flatten: 'true'
          clean: 'true'

      - name: Make Dockerfile
        id: make-dockerfile
        uses: apikcloud/make-dockerfile-action@v1
        with:
          version: ${{ inputs.odoo_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (LIL)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LIL_DOCKER_USERNAME }}
          password: ${{ secrets.LIL_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image_name }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}